### ISSUE TITLE
remove repeated snippets in Humans

### ISSUE THREAD

**Issue by tshepang** [Pylons/pyramid_tutorials#15]
I don't see what the need is to include code snippets (files in this case) between the progressive steps when nothing has changed between current step and previous one. Can we just remove those to:

* avoid redundancy
* make it clearer what has changed between the steps

**Comment by stevepiercy** [comment]
Closing this issue as there is no specific reference to duplicated code snippets.

@tshepang Feel free to reopen this issue citing any specific duplication.

@pauleveritt Please create new issues or PRs with your list of notes, if you think doing these items are necessary.

Thank you!

**Comment by pauleveritt** [comment]
Thanks for closing this, Steve. Really, the "Humans" tutorial is superseded by the official Quick Tutorial. I don't know what we should do for such a case. If we remove it, we break URLs. If we leave it in, with a banner saying "Obsolete" (like old branches of Pyramid docs), we still have something misleading out there.

Any thoughts?

**Comment by tshepang** [comment]
I vote for breaking the URLs

**Comment by stevepiercy** [comment]
@pauleveritt Where are the URLs that would be broken?

* URLs relative to this repo should get broken and go away, except for a milepost, like this one (https://github.com/Pylons/pyramid_tutorials/blob/master/getting_started/index.rst). (RTD builds for pyramid_tutorials are broken at the moment because I'm dumb and forgot to ask @blaflamme to make me an Owner.)
* URLs on search engines, meh, don't care, indexing will fix that eventually.
* URLs in other Pylons Project repos that point to this repo, let's find and fix 'em.

**Comment by pauleveritt** [comment]
I mostly meant search engines. I don’t know if there are any old blog posts or stack overflow things out there.

—Paul

**Comment by stevepiercy** [comment]
This might handle it.
https://docs.readthedocs.org/en/latest/user-defined-redirects.html

**Comment by stevepiercy** [comment]
Nope. It doesn't handle it, except on a page-by-page basis, which is a ridiculous amount of work. Also RTD does not yet provide a default 404 page per project. I'm inclined to let this one go by the wayside.

@pauleveritt Should I get rid of Humans, too, like I did the Getting Started? http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/getting_started/index.html

**Comment by pauleveritt** [comment]
Agreed, and yes to humans.

—Paul
