### ISSUE TITLE
Remove redundant getting_started tutorial

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_tutorials#88]
[pyramid_tutorials/getting_started](https://github.com/Pylons/pyramid_tutorials/tree/master/getting_started) may be out of date and out of sync with the official docs. In fact, @pauleveritt should it be removed/refer to the official docs [Quick Tutorial](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html)? I think it is confusing. See https://github.com/Pylons/pyramid/pull/1650

**Comment by pauleveritt** [comment]
I agree that the tutorials in general need a complete housecleaning. In general, our stance has been that these tutorials are a community project, not core documentation. As such, if someone contributes a tutorial that then gets out of date, well, that happens in open source. Of course, since the tutorial in question is *mine*...[wink]

I don't quite know the deprecation policy for Pyramid docs vis a vis broken links. Do we just put a banner on all the pages saying it is out of date and leave it in place? Do we delete all the content and leave the page? Do we delete the pages? Do we remove the entire tutorial (which would be the ideal option)?

**Comment by stevepiercy** [comment]
@pauleveritt I think the presence of the same content in two places, yet different versions, is harmful. AFAIK, no other tutorial's content is also in the official docs and two places. It's confusing to visitors and it requires additional overhead and maintenance.

In this special case, we should:

1. add a milestone page at http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/getting_started/index.html which directs visitors to the current content at http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html
2. remove all other content from pyramid_tutorials/getting_started

**Comment by stevepiercy** [comment]
@pauleveritt Would you please review PR #92? I would like to merge it, unless you say "nope".
